# Generated by Django 5.0.6 on 2024-05-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobilier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
